matrix:
  include:
    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp27-cp27m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp27-cp27mu
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp35-cp35m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp36-cp36m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp37-cp37m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp38-cp38
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp27-cp27m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp27-cp27mu
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp35-cp35m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp36-cp36m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp37-cp37m
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: PYTHON=python DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp38-cp38
      install:
        - $PYTHON cibuild.py twine
        - docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build manylinux1_i686

    - os: osx
      osx_image: xcode11
      language: generic
      env: PYTHON=python2 PYVER=2.7 URL=https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg
      install:
        - ./travis-osx.sh
        - sudo $PYTHON cibuild.py twine
        - $PYTHON cibuild.py prepare
      script:
        - $PYTHON cibuild.py build macosx_10_9_intel

    - os: osx
      osx_image: xcode11
      language: generic
      env: PYTHON=python3 PYVER=3.6 URL=https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.6.pkg
      install:
        - ./travis-osx.sh
        - sudo $PYTHON cibuild.py twine
        - $PYTHON cibuild.py prepare
      script:
        - $PYTHON cibuild.py build macosx_10_9_intel

    - os: osx
      osx_image: xcode11
      language: generic
      env: PYTHON=python3 PYVER=3.7 URL=https://www.python.org/ftp/python/3.7.4/python-3.7.4-macosx10.9.pkg
      install:
        - ./travis-osx.sh
        - sudo $PYTHON cibuild.py twine
        - $PYTHON cibuild.py prepare
      script:
        - $PYTHON cibuild.py build macosx_10_9_intel

    - os: osx
      osx_image: xcode11
      language: generic
      env: PYTHON=python3 PYVER=3.8 URL=https://www.python.org/ftp/python/3.8.2/python-3.8.2-macosx10.9.pkg
      install:
        - ./travis-osx.sh
        - sudo $PYTHON cibuild.py twine
        - $PYTHON cibuild.py prepare
      script:
        - $PYTHON cibuild.py build macosx_10_9_intel

after_success:
  - $PYTHON cibuild.py upload
